import { createActivity, createTask, createWorkflow, TaskStatus } from './domain.js';
export class Orchestrator {
  constructor(agents) { this.agents=new Map(agents.map(a=>[a.id,a])); this.tasks=new Map(); this.workflows=new Map(); this.activities=[]; }
  emit(eventType,message,meta={}) { const event=createActivity(eventType,message,meta); this.activities.unshift(event); return event; }
  startWorkflow(goal) { const workflow=createWorkflow(goal); this.workflows.set(workflow.id,workflow); this.emit('WORKFLOW_CREATED','Manager received new goal',{workflowId:workflow.id,agentId:'manager'}); return workflow; }
  createTask(workflowId,input) { const task=createTask(input); this.tasks.set(task.id,task); const w=this.workflows.get(workflowId); if(w) { w.taskIds.push(task.id); w.currentTaskId=task.id; w.updatedAt=new Date().toISOString(); } this.emit('TASK_CREATED',`Manager created task ${task.id}`,{workflowId,taskId:task.id,agentId:'manager'}); return task; }
  async execute(workflowId,taskId) { const task=this.tasks.get(taskId); if(!task) throw new Error('Task not found'); const agent=this.agents.get(task.agentId); if(!agent) throw new Error(`Agent not found: ${task.agentId}`); task.status=TaskStatus.RUNNING; task.startedAt=new Date().toISOString(); this.emit('AGENT_STARTED',`${agent.name} started`,{workflowId,taskId,agentId:agent.id}); try { task.output=await agent.execute(task); task.status=TaskStatus.COMPLETED; task.completedAt=new Date().toISOString(); this.emit('TASK_COMPLETED',`${agent.name} completed`,{workflowId,taskId,agentId:agent.id}); return task; } catch(error) { task.status=TaskStatus.FAILED; task.error=error.message; this.emit('TASK_FAILED',`${agent.name} failed: ${error.message}`,{workflowId,taskId,agentId:agent.id}); throw error; } }
  retry(taskId) { const task=this.tasks.get(taskId); if(!task) throw new Error('Task not found'); task.retryCount++; task.status=TaskStatus.PENDING; task.error=null; return task; }
  completeWorkflow(workflowId) { const w=this.workflows.get(workflowId); if(!w) throw new Error('Workflow not found'); w.status=TaskStatus.COMPLETED; w.completedAt=new Date().toISOString(); w.updatedAt=w.completedAt; this.emit('WORKFLOW_COMPLETED','Final result approved',{workflowId,agentId:'manager'}); return w; }
}
