import http from 'node:http';
import { AiGateway } from './ai.js';
import { agents } from './domain.js';
import { ManagerAgent, ResearcherAgent, WriterAgent, ReviewerAgent } from './agents.js';
import { Orchestrator } from './orchestrator.js';
const ai=new AiGateway();
const definitions={manager:ManagerAgent,researcher:ResearcherAgent,writer:WriterAgent,reviewer:ReviewerAgent};
const runtimeAgents=agents.map(d=>new definitions[d.id](d,ai));
const orchestrator=new Orchestrator(runtimeAgents);
function json(res,status,data){res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':'*'});res.end(JSON.stringify(data));}
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>AI Agent Content HQ</title><style>body{margin:0;background:#0b1020;color:#e8edf7;font:14px system-ui}header{padding:20px 28px;border-bottom:1px solid #26304a;display:flex;justify-content:space-between}.ok{color:#45e0a2}.layout{display:grid;grid-template-columns:190px 1fr;min-height:calc(100vh - 70px)}aside{padding:24px;border-right:1px solid #26304a}aside div{padding:12px 8px;color:#9aa7bd}.main{padding:28px}.stats,.agents{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card{background:#11182a;border:1px solid #26304a;border-radius:12px;padding:18px}.muted{color:#8996ad}.badge{display:inline-block;margin-top:10px;padding:4px 8px;border-radius:20px;background:#1d2940}.workflow{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.node{padding:14px 18px;border:1px solid #34425e;border-radius:10px}.feed{margin-top:10px}.event{padding:10px 0;border-bottom:1px solid #202b43}</style></head><body><header><strong>AI Agent Content HQ</strong><span>System status: <b class="ok">ONLINE</b></span></header><div class="layout"><aside><div>Dashboard</div><div>Agents</div><div>Tasks</div><div>Workflows</div><div>Activity</div><div>Content</div><div>Settings</div></aside><main class="main"><h2>Today's overview</h2><section class="stats"><div class="card"><b>Active Tasks</b><h2 id="active">0</h2></div><div class="card"><b>Completed</b><h2 id="done">0</h2></div><div class="card"><b>Waiting</b><h2>0</h2></div><div class="card"><b>Failed</b><h2 id="failed">0</h2></div></section><h2>Agent team</h2><section class="agents" id="agents"></section><h2>Live delegation</h2><section class="card workflow"><span class="node">USER</span>→<span class="node">MANAGER</span>→<span class="node">RESEARCHER</span>→<span class="node">WRITER</span>→<span class="node">REVIEWER</span>→<span class="node">MANAGER</span>→<span class="node">FINAL</span></section><h2>Activity feed</h2><section class="card feed" id="feed"></section></main></div><script>async function refresh(){let d=await fetch('/api/state').then(r=>r.json());agents.innerHTML=d.agents.map(a=>'<div class="card"><b>'+a.name+'</b><div class="muted">'+a.role+'</div><span class="badge">'+a.status+'</span><p>Current task: '+(a.currentTask||'None')+'</p></div>').join('');feed.innerHTML=d.activities.slice(0,12).map(e=>'<div class="event"><small>'+new Date(e.timestamp).toLocaleTimeString()+'</small> '+e.message+'</div>').join('')||'<div class="muted">No activity yet</div>';active.textContent=[...d.tasks].filter(x=>['RUNNING','ASSIGNED'].includes(x.status)).length;done.textContent=[...d.tasks].filter(x=>x.status==='COMPLETED').length;failed.textContent=[...d.tasks].filter(x=>x.status==='FAILED').length}refresh();setInterval(refresh,2000)</script></body></html>`;
const server=http.createServer(async(req,res)=>{if(req.method==='GET'&&req.url==='/'){res.writeHead(200,{'content-type':'text/html'});return res.end(html)}if(req.method==='GET'&&req.url==='/api/state')return json(res,200,{agents:runtimeAgents.map(a=>({id:a.id,name:a.name,role:a.role,status:a.status,currentTask:a.currentTask})),tasks:[...orchestrator.tasks.values()],workflows:[...orchestrator.workflows.values()],activities:orchestrator.activities});if(req.method==='POST'&&req.url==='/api/workflows'){let body='';for await(const c of req)body+=c;const {goal}=JSON.parse(body);const w=orchestrator.startWorkflow(goal);return json(res,201,w)}json(res,404,{error:'Not found'})});server.listen(process.env.PORT||3000,()=>console.log('AI Agent Content HQ listening on port '+(process.env.PORT||3000)));
